dataset: stl10
image_size: 48
eval_file_prefix: STL32
gen_type: t_cnn
gen_path: trained_models/MMDGAN_STL.pth
disc_type: c_sndcgan
disc_path: trained_models/DCGAN_D_STL48_SNGAN_NonSaturating_150001.npz
corr_type: t_sndcgan
corr_path: trained_models/MMDGAN_STL_DRC.pth
f_div: KL
eta: 0.05
gamma: 0.01
save_interval: 5
keep_samples: true
steps: 15
bottom_width: 6
num_imgs: 50000
batch_size: 500
exp_root: ./exps/
z_dim: 32
